### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by klemola** [klemola/foobar2000-web-ui#12]
Mandatory
- [x] Update deps
- [ ] Rewrite client
- [ ] Re-instate client tests
- [ ] Fix known bugs

Optional
- [ ] Show playlist in UI #10 
- [ ] Improve service discovery

**Comment by Akinevz** [comment]
additional request: audio visualisation widgets.
I understand that it's unlikely that there is a way to grab them from the application itself. 
What is your view on implementing a plugin-based system for audio visualisation?
